name: Build Herms binaries

on:
    push:
        # For example...
        paths-ignore:
        - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup stack
        uses: mstksg/setup-stack@v1

      - name: Dependencies
        shell: bash
        run: stack update

      - name: Build
        shell: bash
        run: stack build

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
