name: Build Herms binaries

on:
    push:
        tags:
          - '*'
        # Don't build when these change:
        paths-ignore:
          - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup stack
        uses: mstksg/setup-stack@v1

      - name: Dependencies
        shell: bash
        run: stack update

      - name: Build
        shell: bash
        run: stack build --copy-bins --local-bin-path .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: CHANGELOG.md
          draft: true
          files: |
            herms
            LICENSE
            README.md
            data/config.hs
            data/recipes.yaml
            data/recipes.herms
            # herms needs an installer, for putting config.hs and recipes.yaml in their places.
