name: Format with Ormolu
on:
  - push
  - pull_request
jobs:
  linux:
    name: ormolu
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          path: herms
      - uses: mrkkrp/ormolu-action@v1
        with:
          pattern: |
            herms/app/**/*.hs
            herms/src/**/*.hs
            herms/test/**/*.hs
